import { useMemo, useState } from 'react';
import type { ColDef } from 'ag-grid-community';
import {
  AlertTriangle,
  BookTemplate,
  Building2,
  ClipboardList,
  History,
  KeyRound,
  Layers3,
  ListChecks,
  Plus,
  RefreshCcw,
  Save,
  Search,
  Settings,
  ShieldCheck,
  UserCog,
  Users,
  type LucideIcon
} from 'lucide-react';

import { Button } from '@/shared/components/Button';
import { EnterpriseGrid } from '@/shared/components/grid/EnterpriseGrid';
import { StatCard } from '@/shared/components/StatCard';
import { StatusBadge } from '@/shared/components/StatusBadge';
import {
  useAdminClients,
  useAdminPortfolios,
  useAdministrationMutations,
  useSecurityPermissions,
  useSecurityRoles,
  useSecurityUsers,
  useSystemSettings,
  useWorkflowQueues
} from '../hooks/useAdministration';
import type {
  AdminClient,
  AdminPortfolio,
  AssignmentForm,
  ClientForm,
  PortfolioForm,
  SecurityPermission,
  SecurityRole,
  SecurityUser,
  SystemSetting,
  SystemSettingForm,
  WorkflowQueue,
  WorkflowQueueForm,
  UserForm
} from '../types/administration';

type AdminTab = 'clients' | 'portfolios' | 'queues' | 'settings' | 'users' | 'roles' | 'permissions' | 'templates' | 'audit';

type FilterState = {
  search: string;
  clientId: string;
  module: string;
};

type BackendGapRow = {
  area: string;
  requestedCapability: string;
  currentSupport: string;
  status: 'Backend Gap' | 'Read-only' | 'Configurable';
};

type PermissionMatrixRow = {
  module: string;
  permissions: number;
  examples: string;
  status: string;
};

const pageSize = 25;
const tabs: Array<{ key: AdminTab; label: string; icon: LucideIcon; helper: string }> = [
  { key: 'clients', label: 'Clients', icon: Building2, helper: 'Client master data' },
  { key: 'portfolios', label: 'Portfolios', icon: Layers3, helper: 'Client portfolios' },
  { key: 'queues', label: 'Workflow Queues', icon: ListChecks, helper: 'Operational queues' },
  { key: 'settings', label: 'System Settings', icon: Settings, helper: 'Runtime configuration' },
  { key: 'users', label: 'Users', icon: Users, helper: 'Identity mapping' },
  { key: 'roles', label: 'Roles', icon: ShieldCheck, helper: 'Role catalog' },
  { key: 'permissions', label: 'Permissions', icon: KeyRound, helper: 'Permission matrix' },
  { key: 'templates', label: 'Templates', icon: BookTemplate, helper: 'Backend gap tracker' },
  { key: 'audit', label: 'Audit Readiness', icon: History, helper: 'Security evidence gaps' }
];

const portfolioTypes = [
  { value: 1, label: 'Credit Card' },
  { value: 2, label: 'Consumer Loan' },
  { value: 3, label: 'Medical' },
  { value: 4, label: 'Commercial' }
];

const moduleOptions = ['', 'Placement', 'Claims', 'Scrub', 'Monitoring', 'Documents', 'NDC', 'Administration', 'Reporting'];

const templateGapRows: BackendGapRow[] = [
  { area: 'Document Templates', requestedCapability: 'Create/update filing, POC, exhibit, receipt, and notice templates', currentSupport: 'Documents can be generated by templateType string only; no template CRUD API exists.', status: 'Backend Gap' },
  { area: 'Email Templates', requestedCapability: 'Maintain client/court/attorney notification templates', currentSupport: 'No email template endpoints in Swagger.', status: 'Backend Gap' },
  { area: 'Timeline Templates', requestedCapability: 'Configure reusable timeline event text by workflow action', currentSupport: 'Timeline event creation exists; no template-management endpoints.', status: 'Backend Gap' },
  { area: 'Workflow Templates', requestedCapability: 'Configure workflow steps, SLAs, queue transitions, and assignment rules', currentSupport: 'Workflow queue create/list exists only; no workflow definition API.', status: 'Backend Gap' },
  { area: 'Notification Templates', requestedCapability: 'Configure notification body, severity, delivery channel, and deep link behavior', currentSupport: 'No notification or notification-template endpoint.', status: 'Backend Gap' }
];

const auditGapRows: BackendGapRow[] = [
  { area: 'Audit Trail', requestedCapability: 'Search user/action/module audit events', currentSupport: 'No audit search endpoint in Swagger.', status: 'Backend Gap' },
  { area: 'Login History', requestedCapability: 'Review login events, failed attempts, IP/device metadata', currentSupport: 'Users expose lastLogin-like fields when returned; no login-history API.', status: 'Backend Gap' },
  { area: 'Session Management', requestedCapability: 'List/revoke active sessions', currentSupport: 'No session endpoint in Swagger.', status: 'Backend Gap' },
  { area: 'Role Assignment History', requestedCapability: 'Track role/client access changes over time', currentSupport: 'Assign role/client endpoints exist; no assignment history endpoint.', status: 'Backend Gap' },
  { area: 'Permission Matrix Editing', requestedCapability: 'Create/update roles, permissions, and role-permission mappings', currentSupport: 'Role and permission catalogs are read-only in Swagger.', status: 'Backend Gap' }
];

function toNumberOrUndefined(value: string | number | '') {
  if (value === '') return undefined;
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : undefined;
}

function formatDate(value?: string | null) {
  if (!value) return '-';
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat('en-US', { month: 'short', day: '2-digit', year: 'numeric' }).format(date);
}

function boolBadge(value: boolean | null | undefined) {
  if (value === null || value === undefined) return <StatusBadge label="Unknown" tone="neutral" />;
  return <StatusBadge label={value ? 'Active' : 'Inactive'} tone={value ? 'success' : 'neutral'} />;
}

function safeText(value?: string | number | null) {
  return value === null || value === undefined || value === '' ? '-' : String(value);
}

function gapBadge(status: BackendGapRow['status']) {
  if (status === 'Backend Gap') return <StatusBadge label="Backend Gap" tone="warning" />;
  if (status === 'Read-only') return <StatusBadge label="Read-only" tone="neutral" />;
  return <StatusBadge label="Configurable" tone="success" />;
}

export function AdministrationCenterPage() {
  const [activeTab, setActiveTab] = useState<AdminTab>('clients');
  const [page, setPage] = useState(1);
  const [filters, setFilters] = useState<FilterState>({ search: '', clientId: '', module: '' });
  const [submittedFilters, setSubmittedFilters] = useState<FilterState>({ search: '', clientId: '', module: '' });
  const [hasSearched, setHasSearched] = useState(true);
  const [message, setMessage] = useState<string | null>(null);
  const [clientForm, setClientForm] = useState<ClientForm>({ code: '', name: '' });
  const [portfolioForm, setPortfolioForm] = useState<PortfolioForm>({ clientId: 0, portfolioNumber: '', portfolioName: '', portfolioType: 1 });
  const [queueForm, setQueueForm] = useState<WorkflowQueueForm>({ code: '', name: '', module: 'Placement', description: '' });
  const [settingForm, setSettingForm] = useState<SystemSettingForm>({ key: '', value: '', description: '' });
  const [userForm, setUserForm] = useState<UserForm>({ externalIdentityId: '', email: '', displayName: '' });
  const [assignmentForm, setAssignmentForm] = useState<AssignmentForm>({ userId: '', roleId: '', clientId: '' });

  const searchRequest = useMemo(() => ({ page, pageSize, search: submittedFilters.search || undefined }), [page, submittedFilters.search]);
  const portfolioRequest = useMemo(() => ({ ...searchRequest, clientId: toNumberOrUndefined(submittedFilters.clientId) }), [searchRequest, submittedFilters.clientId]);
  const queueRequest = useMemo(() => ({ ...searchRequest, module: submittedFilters.module || undefined }), [searchRequest, submittedFilters.module]);

  const clientsQuery = useAdminClients(searchRequest, hasSearched && activeTab === 'clients');
  const portfoliosQuery = useAdminPortfolios(portfolioRequest, hasSearched && activeTab === 'portfolios');
  const queuesQuery = useWorkflowQueues(queueRequest, hasSearched && activeTab === 'queues');
  const settingsQuery = useSystemSettings(searchRequest, hasSearched && activeTab === 'settings');
  const usersQuery = useSecurityUsers(searchRequest, hasSearched && activeTab === 'users');
  const rolesQuery = useSecurityRoles(searchRequest, hasSearched && (activeTab === 'roles' || activeTab === 'users'));
  const permissionsQuery = useSecurityPermissions(searchRequest, hasSearched && activeTab === 'permissions');
  const mutations = useAdministrationMutations();

  const permissionMatrixRows = useMemo<PermissionMatrixRow[]>(() => {
    const grouped = new Map<string, SecurityPermission[]>();
    for (const permission of permissionsQuery.data?.items ?? []) {
      const moduleName = permission.module || 'Unclassified';
      grouped.set(moduleName, [...(grouped.get(moduleName) ?? []), permission]);
    }
    return Array.from(grouped.entries()).map(([module, permissions]) => ({
      module,
      permissions: permissions.length,
      examples: permissions.slice(0, 4).map((permission) => permission.code || permission.name || `Permission ${permission.permissionId}`).join(', ') || '-',
      status: 'Catalog from API; assignment editing not exposed'
    }));
  }, [permissionsQuery.data?.items]);

  const activeResult = activeTab === 'clients' ? clientsQuery.data
    : activeTab === 'portfolios' ? portfoliosQuery.data
      : activeTab === 'queues' ? queuesQuery.data
        : activeTab === 'settings' ? settingsQuery.data
          : activeTab === 'users' ? usersQuery.data
            : activeTab === 'roles' ? rolesQuery.data
              : activeTab === 'permissions' ? permissionsQuery.data
                : undefined;
  const activeLoading = clientsQuery.isFetching || portfoliosQuery.isFetching || queuesQuery.isFetching || settingsQuery.isFetching || usersQuery.isFetching || rolesQuery.isFetching || permissionsQuery.isFetching;
  const activeError = clientsQuery.isError || portfoliosQuery.isError || queuesQuery.isError || settingsQuery.isError || usersQuery.isError || rolesQuery.isError || permissionsQuery.isError;
  const totalPages = Math.max(1, Math.ceil((activeResult?.totalCount ?? 0) / pageSize));

  const clientColumns = useMemo<ColDef<AdminClient>[]>(() => [
    { headerName: 'Client', field: 'name', pinned: 'left', minWidth: 250, cellRenderer: ({ data }: { data?: AdminClient }) => <div className="grid-primary-cell"><strong>{safeText(data?.name)}</strong><span>{safeText(data?.code)}</span></div> },
    { headerName: 'Client Id', field: 'clientId', minWidth: 130 },
    { headerName: 'Status', field: 'isActive', minWidth: 140, cellRenderer: ({ data }: { data?: AdminClient }) => boolBadge(data?.isActive) },
    { headerName: 'Created', field: 'createdUtc', minWidth: 160, valueFormatter: ({ value }) => formatDate(value) },
    { headerName: 'Modified', field: 'modifiedUtc', minWidth: 160, valueFormatter: ({ value }) => formatDate(value) }
  ], []);

  const portfolioColumns = useMemo<ColDef<AdminPortfolio>[]>(() => [
    { headerName: 'Portfolio', field: 'portfolioName', pinned: 'left', minWidth: 270, cellRenderer: ({ data }: { data?: AdminPortfolio }) => <div className="grid-primary-cell"><strong>{safeText(data?.portfolioName)}</strong><span>{safeText(data?.portfolioNumber)}</span></div> },
    { headerName: 'Client', field: 'clientName', minWidth: 220, valueFormatter: ({ value }) => safeText(value) },
    { headerName: 'Client Id', field: 'clientId', minWidth: 130, valueFormatter: ({ value }) => safeText(value) },
    { headerName: 'Type', field: 'portfolioTypeName', minWidth: 160, valueFormatter: ({ data }) => safeText(data?.portfolioTypeName ?? data?.portfolioType) },
    { headerName: 'Status', field: 'isActive', minWidth: 140, cellRenderer: ({ data }: { data?: AdminPortfolio }) => boolBadge(data?.isActive) }
  ], []);

  const queueColumns = useMemo<ColDef<WorkflowQueue>[]>(() => [
    { headerName: 'Queue', field: 'name', pinned: 'left', minWidth: 260, cellRenderer: ({ data }: { data?: WorkflowQueue }) => <div className="grid-primary-cell"><strong>{safeText(data?.name)}</strong><span>{safeText(data?.code)}</span></div> },
    { headerName: 'Module', field: 'module', minWidth: 160, valueFormatter: ({ value }) => safeText(value) },
    { headerName: 'Description', field: 'description', minWidth: 300, valueFormatter: ({ value }) => safeText(value) },
    { headerName: 'Status', field: 'isActive', minWidth: 140, cellRenderer: ({ data }: { data?: WorkflowQueue }) => boolBadge(data?.isActive) }
  ], []);

  const settingsColumns = useMemo<ColDef<SystemSetting>[]>(() => [
    { headerName: 'Setting', field: 'key', pinned: 'left', minWidth: 260, cellRenderer: ({ data }: { data?: SystemSetting }) => <div className="grid-primary-cell"><strong>{safeText(data?.key)}</strong><span>{safeText(data?.description)}</span></div> },
    { headerName: 'Value', field: 'value', minWidth: 300, valueFormatter: ({ data }) => data?.isEncrypted ? '••••••••' : safeText(data?.value) },
    { headerName: 'Encrypted', field: 'isEncrypted', minWidth: 140, cellRenderer: ({ data }: { data?: SystemSetting }) => <StatusBadge label={data?.isEncrypted ? 'Protected' : 'Plain'} tone={data?.isEncrypted ? 'warning' : 'neutral'} /> },
    { headerName: 'Updated', field: 'updatedUtc', minWidth: 160, valueFormatter: ({ value }) => formatDate(value) }
  ], []);

  const usersColumns = useMemo<ColDef<SecurityUser>[]>(() => [
    { headerName: 'User', field: 'displayName', pinned: 'left', minWidth: 280, cellRenderer: ({ data }: { data?: SecurityUser }) => <div className="grid-primary-cell"><strong>{safeText(data?.displayName)}</strong><span>{safeText(data?.email)}</span></div> },
    { headerName: 'User Id', field: 'userId', minWidth: 120 },
    { headerName: 'External Identity', field: 'externalIdentityId', minWidth: 240, valueFormatter: ({ value }) => safeText(value) },
    { headerName: 'Status', field: 'isActive', minWidth: 140, cellRenderer: ({ data }: { data?: SecurityUser }) => boolBadge(data?.isActive) },
    { headerName: 'Last Login', field: 'lastLoginUtc', minWidth: 160, valueFormatter: ({ value }) => formatDate(value) }
  ], []);

  const roleColumns = useMemo<ColDef<SecurityRole>[]>(() => [
    { headerName: 'Role', field: 'name', pinned: 'left', minWidth: 260, cellRenderer: ({ data }: { data?: SecurityRole }) => <div className="grid-primary-cell"><strong>{safeText(data?.name)}</strong><span>{safeText(data?.code)}</span></div> },
    { headerName: 'Role Id', field: 'roleId', minWidth: 120 },
    { headerName: 'Description', field: 'description', minWidth: 320, valueFormatter: ({ value }) => safeText(value) },
    { headerName: 'Status', field: 'isActive', minWidth: 140, cellRenderer: ({ data }: { data?: SecurityRole }) => boolBadge(data?.isActive) }
  ], []);

  const permissionColumns = useMemo<ColDef<SecurityPermission>[]>(() => [
    { headerName: 'Permission', field: 'name', pinned: 'left', minWidth: 290, cellRenderer: ({ data }: { data?: SecurityPermission }) => <div className="grid-primary-cell"><strong>{safeText(data?.name)}</strong><span>{safeText(data?.code)}</span></div> },
    { headerName: 'Module', field: 'module', minWidth: 170, valueFormatter: ({ value }) => safeText(value) },
    { headerName: 'Description', field: 'description', minWidth: 360, valueFormatter: ({ value }) => safeText(value) }
  ], []);

  const gapColumns = useMemo<ColDef<BackendGapRow>[]>(() => [
    { headerName: 'Area', field: 'area', pinned: 'left', minWidth: 220, cellRenderer: ({ data }: { data?: BackendGapRow }) => <div className="grid-primary-cell"><strong>{safeText(data?.area)}</strong><span>{safeText(data?.currentSupport)}</span></div> },
    { headerName: 'Requested Capability', field: 'requestedCapability', minWidth: 360, valueFormatter: ({ value }) => safeText(value) },
    { headerName: 'Current Support', field: 'currentSupport', minWidth: 360, valueFormatter: ({ value }) => safeText(value) },
    { headerName: 'Status', field: 'status', minWidth: 160, cellRenderer: ({ data }: { data?: BackendGapRow }) => data ? gapBadge(data.status) : null }
  ], []);

  const permissionMatrixColumns = useMemo<ColDef<PermissionMatrixRow>[]>(() => [
    { headerName: 'Module', field: 'module', pinned: 'left', minWidth: 220 },
    { headerName: 'Permission Count', field: 'permissions', minWidth: 160 },
    { headerName: 'Examples', field: 'examples', minWidth: 420, valueFormatter: ({ value }) => safeText(value) },
    { headerName: 'Status', field: 'status', minWidth: 300, valueFormatter: ({ value }) => safeText(value) }
  ], []);

  function search() {
    setPage(1);
    setSubmittedFilters(filters);
    setHasSearched(true);
  }

  function reset() {
    const cleared = { search: '', clientId: '', module: '' };
    setFilters(cleared);
    setSubmittedFilters(cleared);
    setPage(1);
    setHasSearched(true);
  }

  function switchTab(tab: AdminTab) {
    setActiveTab(tab);
    setPage(1);
    setMessage(null);
  }

  async function submitClient() {
    await mutations.createClient.mutateAsync({ code: clientForm.code, name: clientForm.name });
    setClientForm({ code: '', name: '' });
    setMessage('Client saved successfully.');
  }

  async function submitPortfolio() {
    await mutations.createPortfolio.mutateAsync(portfolioForm);
    setPortfolioForm({ clientId: 0, portfolioNumber: '', portfolioName: '', portfolioType: 1 });
    setMessage('Portfolio saved successfully.');
  }

  async function submitQueue() {
    await mutations.createQueue.mutateAsync(queueForm);
    setQueueForm({ code: '', name: '', module: 'Placement', description: '' });
    setMessage('Workflow queue saved successfully.');
  }

  async function submitSetting() {
    await mutations.upsertSetting.mutateAsync(settingForm);
    setSettingForm({ key: '', value: '', description: '' });
    setMessage('System setting saved successfully.');
  }

  async function submitUser() {
    await mutations.createUser.mutateAsync(userForm);
    setUserForm({ externalIdentityId: '', email: '', displayName: '' });
    setMessage('User saved successfully.');
  }

  async function submitRoleAssignment() {
    const userId = Number(assignmentForm.userId);
    const roleId = Number(assignmentForm.roleId);
    if (!Number.isFinite(userId) || !Number.isFinite(roleId) || userId <= 0 || roleId <= 0) return;
    await mutations.assignRole.mutateAsync({ userId, roleId });
    setAssignmentForm((current) => ({ ...current, roleId: '' }));
    setMessage('Role assigned successfully.');
  }

  async function submitClientAssignment() {
    const userId = Number(assignmentForm.userId);
    const clientId = Number(assignmentForm.clientId);
    if (!Number.isFinite(userId) || !Number.isFinite(clientId) || userId <= 0 || clientId <= 0) return;
    await mutations.assignClient.mutateAsync({ userId, clientId });
    setAssignmentForm((current) => ({ ...current, clientId: '' }));
    setMessage('Client access assigned successfully.');
  }

  const currentRows = activeTab === 'clients' ? clientsQuery.data?.items ?? []
    : activeTab === 'portfolios' ? portfoliosQuery.data?.items ?? []
      : activeTab === 'queues' ? queuesQuery.data?.items ?? []
        : activeTab === 'settings' ? settingsQuery.data?.items ?? []
          : activeTab === 'users' ? usersQuery.data?.items ?? []
            : activeTab === 'roles' ? rolesQuery.data?.items ?? []
              : activeTab === 'permissions' ? permissionsQuery.data?.items ?? []
                : activeTab === 'templates' ? templateGapRows
                  : auditGapRows;

  const currentColumns = activeTab === 'clients' ? clientColumns
    : activeTab === 'portfolios' ? portfolioColumns
      : activeTab === 'queues' ? queueColumns
        : activeTab === 'settings' ? settingsColumns
          : activeTab === 'users' ? usersColumns
            : activeTab === 'roles' ? roleColumns
              : activeTab === 'permissions' ? permissionColumns
                : gapColumns;

  const recordsLabel = activeTab === 'templates' ? templateGapRows.length
    : activeTab === 'audit' ? auditGapRows.length
      : activeResult?.totalCount ?? 0;

  return (
    <div className="enterprise-page admin-page">
      <section className="placement-hero xocket-card admin-hero">
        <div>
          <h1>Administration, Templates & Security</h1>
          <p>LP-08 consolidates client/portfolio setup, workflow queue configuration, system settings, security users, role assignment, client access assignment, permission catalog review, and explicit backend gaps for templates/audit.</p>
        </div>
        <div className="placement-hero-actions">
          <Button variant="secondary" onClick={() => reset()}><RefreshCcw size={16} /> Reset</Button>
        </div>
      </section>

      <section className="stat-grid placement-stat-grid admin-stat-grid">
        <StatCard icon={<Building2 size={22} />} value={clientsQuery.data?.totalCount ?? '-'} label="Clients" helper="Client master records" tone="primary" />
        <StatCard icon={<Users size={22} />} value={usersQuery.data?.totalCount ?? '-'} label="Users" helper="Security principals" tone="success" />
        <StatCard icon={<ShieldCheck size={22} />} value={rolesQuery.data?.totalCount ?? '-'} label="Roles" helper="Role catalog" tone="warning" />
        <StatCard icon={<AlertTriangle size={22} />} value={templateGapRows.length + auditGapRows.length} label="Backend Gaps" helper="Templates and audit APIs" tone="info" />
      </section>

      <section className="xocket-card admin-tabs-card">
        <div className="admin-tab-row admin-tab-row-lp08">
          {tabs.map((tab) => {
            const Icon = tab.icon;
            return (
              <button key={tab.key} className={`admin-tab ${activeTab === tab.key ? 'active' : ''}`} onClick={() => switchTab(tab.key)} type="button">
                <Icon size={18} />
                <span>{tab.label}</span>
                <small>{tab.helper}</small>
              </button>
            );
          })}
        </div>
      </section>

      <section className="xocket-card placement-filter-card admin-filter-card">
        <div className="xocket-card-header">
          <div>
            <h2 className="xocket-card-title">Search {tabs.find((tab) => tab.key === activeTab)?.label}</h2>
            <p className="xocket-card-subtitle">Search-first server-side pagination where Swagger exposes a list endpoint. Template and audit tabs intentionally document backend gaps.</p>
          </div>
          <span className="xocket-pill admin-pill">{recordsLabel} records</span>
        </div>
        <div className="placement-filter-row admin-filter-row">
          <div className="evictsure-form-group">
            <span className="evictsure-form-label">Search</span>
            <input className="evictsure-form-input" value={filters.search} disabled={activeTab === 'templates' || activeTab === 'audit'} onChange={(event) => setFilters((current) => ({ ...current, search: event.target.value }))} placeholder="Code, name, email, module..." />
          </div>
          {activeTab === 'portfolios' ? (
            <div className="evictsure-form-group">
              <span className="evictsure-form-label">Client Id</span>
              <input className="evictsure-form-input" value={filters.clientId} onChange={(event) => setFilters((current) => ({ ...current, clientId: event.target.value }))} placeholder="Client Id" />
            </div>
          ) : null}
          {activeTab === 'queues' ? (
            <div className="evictsure-form-group">
              <span className="evictsure-form-label">Module</span>
              <select className="evictsure-form-input" value={filters.module} onChange={(event) => setFilters((current) => ({ ...current, module: event.target.value }))}>
                {moduleOptions.map((option) => <option key={option} value={option}>{option || 'All modules'}</option>)}
              </select>
            </div>
          ) : null}
          <div className="placement-filter-actions admin-filter-actions">
            <Button onClick={search} disabled={activeTab === 'templates' || activeTab === 'audit'}><Search size={16} /> Search</Button>
            <Button variant="secondary" onClick={reset}>Clear</Button>
          </div>
        </div>
      </section>

      {activeTab === 'permissions' ? (
        <section className="xocket-card admin-matrix-card">
          <div className="xocket-card-header">
            <div>
              <h2 className="xocket-card-title"><ClipboardList size={18} /> Permission Matrix Summary</h2>
              <p className="xocket-card-subtitle">Groups the read-only permission catalog by module. Role-permission editing is a backend gap because no mapping endpoint exists.</p>
            </div>
          </div>
          <EnterpriseGrid rows={permissionMatrixRows} columns={permissionMatrixColumns} isLoading={permissionsQuery.isFetching} height={260} emptyMessage="Search permissions to build the module matrix." />
        </section>
      ) : null}

      {message ? <div className="xocket-alert xocket-alert-success admin-message">{message}</div> : null}
      {activeError ? <div className="xocket-alert xocket-alert-danger admin-message">Unable to load administration data. Check API availability and permissions.</div> : null}

      <section className="admin-layout-grid">
        <div className="xocket-card admin-grid-card">
          <div className="xocket-card-header">
            <div>
              <h2 className="xocket-card-title">{tabs.find((tab) => tab.key === activeTab)?.label}</h2>
              <p className="xocket-card-subtitle">{activeTab === 'templates' || activeTab === 'audit' ? 'Backend gap register' : `Current page ${page} of ${totalPages}`}</p>
            </div>
            {activeTab === 'templates' || activeTab === 'audit'
              ? <span className="xocket-pill admin-pill">Needs Backend</span>
              : activeLoading ? <span className="xocket-pill admin-pill">Loading</span> : <span className="xocket-pill admin-pill">Live API</span>}
          </div>
          <EnterpriseGrid rows={currentRows as object[]} columns={currentColumns as ColDef<object>[]} isLoading={activeLoading && activeTab !== 'templates' && activeTab !== 'audit'} height={activeTab === 'templates' || activeTab === 'audit' ? 420 : 520} emptyMessage="No administration records matched the current filters." />
          {activeTab !== 'templates' && activeTab !== 'audit' ? (
            <div className="xocket-grid-pagination">
              <Button variant="secondary" disabled={page <= 1} onClick={() => setPage((current) => Math.max(1, current - 1))}>Previous</Button>
              <span>Page {page} of {totalPages}</span>
              <Button variant="secondary" disabled={page >= totalPages} onClick={() => setPage((current) => current + 1)}>Next</Button>
            </div>
          ) : null}
        </div>

        <aside className="xocket-card admin-action-card">
          <div className="xocket-card-header admin-action-header">
            <div>
              <h2 className="xocket-card-title">Actions</h2>
              <p className="xocket-card-subtitle">Context-aware write operations.</p>
            </div>
            <UserCog size={22} />
          </div>
          <div className="admin-action-body">
            {activeTab === 'clients' ? (
              <form className="admin-form" onSubmit={(event) => { event.preventDefault(); void submitClient(); }}>
                <h3><Plus size={17} /> Create Client</h3>
                <label>Code<input required value={clientForm.code ?? ''} onChange={(event) => setClientForm((current) => ({ ...current, code: event.target.value }))} /></label>
                <label>Name<input required value={clientForm.name ?? ''} onChange={(event) => setClientForm((current) => ({ ...current, name: event.target.value }))} /></label>
                <Button disabled={mutations.createClient.isPending}><Save size={16} /> Save Client</Button>
              </form>
            ) : null}

            {activeTab === 'portfolios' ? (
              <form className="admin-form" onSubmit={(event) => { event.preventDefault(); void submitPortfolio(); }}>
                <h3><Plus size={17} /> Create Portfolio</h3>
                <label>Client Id<input required type="number" value={portfolioForm.clientId || ''} onChange={(event) => setPortfolioForm((current) => ({ ...current, clientId: Number(event.target.value) }))} /></label>
                <label>Portfolio Number<input required value={portfolioForm.portfolioNumber ?? ''} onChange={(event) => setPortfolioForm((current) => ({ ...current, portfolioNumber: event.target.value }))} /></label>
                <label>Portfolio Name<input required value={portfolioForm.portfolioName ?? ''} onChange={(event) => setPortfolioForm((current) => ({ ...current, portfolioName: event.target.value }))} /></label>
                <label>Type<select value={portfolioForm.portfolioType} onChange={(event) => setPortfolioForm((current) => ({ ...current, portfolioType: Number(event.target.value) }))}>{portfolioTypes.map((type) => <option key={type.value} value={type.value}>{type.label}</option>)}</select></label>
                <Button disabled={mutations.createPortfolio.isPending}><Save size={16} /> Save Portfolio</Button>
              </form>
            ) : null}

            {activeTab === 'queues' ? (
              <form className="admin-form" onSubmit={(event) => { event.preventDefault(); void submitQueue(); }}>
                <h3><Plus size={17} /> Create Queue</h3>
                <label>Code<input required value={queueForm.code ?? ''} onChange={(event) => setQueueForm((current) => ({ ...current, code: event.target.value }))} /></label>
                <label>Name<input required value={queueForm.name ?? ''} onChange={(event) => setQueueForm((current) => ({ ...current, name: event.target.value }))} /></label>
                <label>Module<select value={queueForm.module ?? ''} onChange={(event) => setQueueForm((current) => ({ ...current, module: event.target.value }))}>{moduleOptions.filter(Boolean).map((option) => <option key={option} value={option}>{option}</option>)}</select></label>
                <label>Description<textarea value={queueForm.description ?? ''} onChange={(event) => setQueueForm((current) => ({ ...current, description: event.target.value }))} /></label>
                <Button disabled={mutations.createQueue.isPending}><Save size={16} /> Save Queue</Button>
              </form>
            ) : null}

            {activeTab === 'settings' ? (
              <form className="admin-form" onSubmit={(event) => { event.preventDefault(); void submitSetting(); }}>
                <h3><Save size={17} /> Upsert Setting</h3>
                <label>Key<input required value={settingForm.key ?? ''} onChange={(event) => setSettingForm((current) => ({ ...current, key: event.target.value }))} /></label>
                <label>Value<input required value={settingForm.value ?? ''} onChange={(event) => setSettingForm((current) => ({ ...current, value: event.target.value }))} /></label>
                <label>Description<textarea value={settingForm.description ?? ''} onChange={(event) => setSettingForm((current) => ({ ...current, description: event.target.value }))} /></label>
                <Button disabled={mutations.upsertSetting.isPending}><Save size={16} /> Save Setting</Button>
              </form>
            ) : null}

            {activeTab === 'users' ? (
              <>
                <form className="admin-form" onSubmit={(event) => { event.preventDefault(); void submitUser(); }}>
                  <h3><Plus size={17} /> Create User</h3>
                  <label>External Identity<input required value={userForm.externalIdentityId ?? ''} onChange={(event) => setUserForm((current) => ({ ...current, externalIdentityId: event.target.value }))} /></label>
                  <label>Email<input required type="email" value={userForm.email ?? ''} onChange={(event) => setUserForm((current) => ({ ...current, email: event.target.value }))} /></label>
                  <label>Display Name<input required value={userForm.displayName ?? ''} onChange={(event) => setUserForm((current) => ({ ...current, displayName: event.target.value }))} /></label>
                  <Button disabled={mutations.createUser.isPending}><Save size={16} /> Save User</Button>
                </form>
                <form className="admin-form admin-nested-form" onSubmit={(event) => { event.preventDefault(); void submitRoleAssignment(); }}>
                  <h3><ShieldCheck size={17} /> Assign Role</h3>
                  <label>User Id<input required type="number" value={assignmentForm.userId} onChange={(event) => setAssignmentForm((current) => ({ ...current, userId: event.target.value }))} /></label>
                  <label>Role Id<input required type="number" value={assignmentForm.roleId} onChange={(event) => setAssignmentForm((current) => ({ ...current, roleId: event.target.value }))} /></label>
                  <Button variant="secondary" disabled={mutations.assignRole.isPending}>Assign Role</Button>
                </form>
                <form className="admin-form admin-nested-form" onSubmit={(event) => { event.preventDefault(); void submitClientAssignment(); }}>
                  <h3><Building2 size={17} /> Assign Client Access</h3>
                  <label>User Id<input required type="number" value={assignmentForm.userId} onChange={(event) => setAssignmentForm((current) => ({ ...current, userId: event.target.value }))} /></label>
                  <label>Client Id<input required type="number" value={assignmentForm.clientId} onChange={(event) => setAssignmentForm((current) => ({ ...current, clientId: event.target.value }))} /></label>
                  <Button variant="secondary" disabled={mutations.assignClient.isPending}>Assign Client</Button>
                </form>
              </>
            ) : null}

            {activeTab === 'roles' || activeTab === 'permissions' ? (
              <div className="admin-readonly-note">
                <ShieldCheck size={22} />
                <h3>Read-only catalog</h3>
                <p>Current Swagger exposes list endpoints for roles and permissions. Create/update and role-permission mapping endpoints are not present, so this UI intentionally keeps the catalog read-only.</p>
              </div>
            ) : null}

            {activeTab === 'templates' ? (
              <div className="admin-readonly-note admin-gap-note">
                <BookTemplate size={22} />
                <h3>Template backend required</h3>
                <p>LP-08 does not invent template CRUD. The UI now documents required template management endpoints and keeps document generation bound to the existing templateType-based APIs.</p>
              </div>
            ) : null}

            {activeTab === 'audit' ? (
              <div className="admin-readonly-note admin-gap-note">
                <History size={22} />
                <h3>Audit backend required</h3>
                <p>Security evidence screens require audit, login history, session, and role assignment history APIs. These are marked as backend gaps until Swagger exposes them.</p>
              </div>
            ) : null}
          </div>
        </aside>
      </section>
    </div>
  );
}
